dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.9.6

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor

script:
- make test
- make vendor-status
- make vet
# We cannot add them back since the symbolic link is missing on the terraform website
# - make website-test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

notifications:
  slack:
    secure: pGccP4Xcn9HxR1kBVQj6r09UK39f5ZvHnI0/EJepHTZkW0Foqs/GjgjS9730ugRdf6kPAzsy2BujosFjK/1kb9m6syYpzK3tnIYVym6HqAUHe8B4jnmCfKFFEcVhVoPM6u8UFbjaPL4MiQG2GK0WeBcslGx532Wr3g9yrdPxj6CsmPSy//GuTFpmkr4iAxfmcV4q+1A2iyzPUH1BAscJFyBxuXHnYz9Wz1ocgEDFOoVIEVvuxYC560QzT0H/3Sias9vTDDTZbXkZpllvAG9dgyfCCKVKqXCr5WAC+fwePclE8M2kTCgomEf90RmFcwr/7KYknYwMVcGuUykp0rmZX//ELSLzRwlvcoY5n1PanXbQvV3H8GLg71sRX8XxRE1AYSFfwXPPWFc2LJEf5p3hZZLT/wtGzp3QDDxrHlEWdrkM6AH6QYUoK5Xa7sHhVGx9MAFSQEwLdoVMJvfrX4woaWpUs8RlKTgpvrKf94Vvdke9jF+Tb3O/u9kfBC6aiRYNjYNrgu0S1mEDJgWtzBwYKhVoXr71AjM0tNLFjXuoXYf/Pmm3jfBkeIJcmCUMB5otblX5IM4eAL/YXFXqLmuBVHDcCI9QsYEaxekifuprgb/WfciK0IwS3qYV7H/9c5wPLHENJoCqFJontaLubg4qHwszrBIgJVH/0yfdZbkBPeQ=
