// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/go-scalingo/v11 (interfaces: DatabasesPreviewService)

// Package scalingo is a generated GoMock package.
package scalingo

import (
	context "context"
	reflect "reflect"

	scalingo "github.com/Scalingo/go-scalingo/v11"
	gomock "go.uber.org/mock/gomock"
)

// MockDatabasesPreviewService is a mock of DatabasesPreviewService interface.
type MockDatabasesPreviewService struct {
	ctrl     *gomock.Controller
	recorder *MockDatabasesPreviewServiceMockRecorder
	isgomock struct{}
}

// MockDatabasesPreviewServiceMockRecorder is the mock recorder for MockDatabasesPreviewService.
type MockDatabasesPreviewServiceMockRecorder struct {
	mock *MockDatabasesPreviewService
}

// NewMockDatabasesPreviewService creates a new mock instance.
func NewMockDatabasesPreviewService(ctrl *gomock.Controller) *MockDatabasesPreviewService {
	mock := &MockDatabasesPreviewService{ctrl: ctrl}
	mock.recorder = &MockDatabasesPreviewServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabasesPreviewService) EXPECT() *MockDatabasesPreviewServiceMockRecorder {
	return m.recorder
}

// DatabaseCreate mocks base method.
func (m *MockDatabasesPreviewService) DatabaseCreate(ctx context.Context, params scalingo.DatabaseCreateParams) (scalingo.DatabaseNG, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseCreate", ctx, params)
	ret0, _ := ret[0].(scalingo.DatabaseNG)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DatabaseCreate indicates an expected call of DatabaseCreate.
func (mr *MockDatabasesPreviewServiceMockRecorder) DatabaseCreate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseCreate", reflect.TypeOf((*MockDatabasesPreviewService)(nil).DatabaseCreate), ctx, params)
}

// DatabaseDestroy mocks base method.
func (m *MockDatabasesPreviewService) DatabaseDestroy(ctx context.Context, appID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseDestroy", ctx, appID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DatabaseDestroy indicates an expected call of DatabaseDestroy.
func (mr *MockDatabasesPreviewServiceMockRecorder) DatabaseDestroy(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseDestroy", reflect.TypeOf((*MockDatabasesPreviewService)(nil).DatabaseDestroy), ctx, appID)
}

// DatabaseShow mocks base method.
func (m *MockDatabasesPreviewService) DatabaseShow(ctx context.Context, appID string) (scalingo.DatabaseNG, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseShow", ctx, appID)
	ret0, _ := ret[0].(scalingo.DatabaseNG)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DatabaseShow indicates an expected call of DatabaseShow.
func (mr *MockDatabasesPreviewServiceMockRecorder) DatabaseShow(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseShow", reflect.TypeOf((*MockDatabasesPreviewService)(nil).DatabaseShow), ctx, appID)
}

// DatabasesList mocks base method.
func (m *MockDatabasesPreviewService) DatabasesList(ctx context.Context) ([]scalingo.DatabaseNG, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabasesList", ctx)
	ret0, _ := ret[0].([]scalingo.DatabaseNG)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DatabasesList indicates an expected call of DatabasesList.
func (mr *MockDatabasesPreviewServiceMockRecorder) DatabasesList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabasesList", reflect.TypeOf((*MockDatabasesPreviewService)(nil).DatabasesList), ctx)
}
